# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3ff11bf970d0f5ad09c185c779d3a2f2d1eea22370439b27852110e1a3f5bd657dd6203f960e2a7ca069e3040648fdfc23cdbfed52c2a22c81fdf9fb25aef86

test:
  secret_key_base: 9f4e34c3274c8f93b37e7d8db5cfc180438d14993a20fbbb58f9fa1ad9bb3bfb5b290b4e2cd3f5f7a77131d757d8b80eeae605396ec1a20f82a1e92222cf7ca0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
